package com.example.shoppingapp.domain.model

data class Order(
    val orderId: String = "", // Generated by Firestore
    val cartItems: List<CartItem> = emptyList(),
    val totalAmount: Double = 0.0,
    val productTotal: Double =0.0,
    val status: String = "Pending", // Default status
    val orderDate: String = "", // Timestamp when order is placed
    val userId: String = "" // using Firebase Auth
)